version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: foxford-web
    ports:
      - "8080:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf