network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      optional: true
  vlans:
    vlan10:
      id: 10
      link: eth0
      addresses: [192.168.10.5/24]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.10.1
    vlan20:
      id: 20
      link: eth0
      addresses: [10.10.20.5/24]
      routes:
        - to: 10.10.30.0/24
          via: 10.10.20.1